#!/usr/bin/sh

if [ "x$XDG_SESSION_TYPE" = "xwayland" ] &&
   [ "x$XDG_SESSION_CLASS" != "xgreeter" ] &&
   [  -n "$SHELL" ] &&
   grep -q "$SHELL" /etc/shells &&
   ! (echo "$SHELL" | grep -q "false") &&
   ! (echo "$SHELL" | grep -q "nologin"); then
  if [ "$1" != '-l' ]; then
    exec bash -c "exec -l '$SHELL' -c '$0 -l $*'"
  else
    shift
  fi
fi

export SWAY_STARTUP="$XDG_RUNTIME_DIR/sway-startup.$$.pipe"
export GTK_USE_PORTAL=0
export GTK_THEME=Adwaita:dark
mkfifo "$SWAY_STARTUP"
exec /usr/bin/sway
read display wayland_display <"$SWAY_STARTUP"
rm "$SWAY_STARTUP"
export DISPLAY="$display" WAYLAND_DISPLAY="$wayland_display"
exec /usr/bin/dbus-update-activation-environment --all
