# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin:$HOME/.node_modules/bin:$HOME/.cargo/bin

export PATH

if [ "$DESKTOP_SESSION" == "sway" ];then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi
